#!/usr/bin/perl
# Perl module
############################################################

my ($ir, $iq, $ix) = @ARGV;
#
# Loop over runs
#

        $rnum=$ir;

# Creat jsub for this job
        $usrnam=`whoami`;
        chop($usrnam);
        $cdir=`pwd`;
        chop($cdir);
        $outhbook="nt10\_tdis\_edx\_$rnum\.hbook";
	$outroots="nt10\_tdis\_edx\_$rnum\.root"; 
	$outlunds="lund\_tdis\_eic$rnum\.dat"; 

        $S_script_name = "jsc$rnum";
        open(SCRIPT_FILE,">$S_script_name");
        printf SCRIPT_FILE "JOBNAME: TDIS_ek$rnum \n";
        printf SCRIPT_FILE "PROJECT: EIC\n";
        printf SCRIPT_FILE "TRACK : simulation \n";
        printf SCRIPT_FILE "SINGLE_JOB: TRUE \n";
        printf SCRIPT_FILE "MEMORY: 9000 MB \n";
        printf SCRIPT_FILE "MAIL: $usrnam\@jlab.org\n";
        printf SCRIPT_FILE "OS: centos65\n";
#        printf SCRIPT_FILE "TIME: 2280\n";
#        printf SCRIPT_FILE "MEMORY: 1900 MB\n";
        printf SCRIPT_FILE "COMMAND: $cdir/RunTDIS_PhaseSpaceBatchK.pl $rnum $iq $ix \n";
        printf SCRIPT_FILE "OTHER_FILES:\n";
        printf SCRIPT_FILE "$cdir/source_codes_TDIS/TDISMC_EICK.cpp \n";
	printf SCRIPT_FILE "$cdir/source_codes_TDIS/TDISMC_EICK.h \n";
        printf SCRIPT_FILE "$cdir/source_codes_TDIS/timhobbs.h \n";           
### copy of deuteron momentum parametrization from data 
        printf SCRIPT_FILE "$cdir/source_codes_TDIS/moment_ld2b.dat \n";
### copy of cteq files 
        printf SCRIPT_FILE "$cdir/source_codes_TDIS/cteq/cteq-database.c \n";
        printf SCRIPT_FILE "$cdir/source_codes_TDIS/cteq/cteqpdf.c \n";
#        printf SCRIPT_FILE "$cdir/source_codes_TDIS/cteq/cteqpdf-f77.c \n";
        printf SCRIPT_FILE "$cdir/source_codes_TDIS/cteq/cteqpdf.h \n";
        printf SCRIPT_FILE "$cdir/source_codes_TDIS/cteq-tbls/ctq66m/ctq66.00.pds \n";
### Misc files;
#        printf SCRIPT_FILE "$cdir/source_codes_TDIS/vwrite_long.kumac \n";
### output file list for save
#        printf SCRIPT_FILE "OUTPUT_DATA: nt10_data.enx_1.hbook\n";
#        printf SCRIPT_FILE "OUTPUT_TEMPLATE:  /lustre/expphy/volatile/eic/parkkj/jleic_kinematics/source_codes2016_for_git_hub_tdis_v1/ifarmbatch/ednt10/$outhbook\n";
        printf SCRIPT_FILE "OUTPUT_DATA: TDIS-MC05x100.root \n"; 
        printf SCRIPT_FILE "OUTPUT_TEMPLATE:  /lustre/expphy/volatile/eic/parkkj/jleic_kinematics/source_codes2016_for_git_hub_tdis_v1/ifarmbatch/edRoots/$outroots \n";
#        I would not store this ASCII data due to huge file size, It will be useful only for GEMC simulation...
#        printf SCRIPT_FILE "OUTPUT_DATA: TDIS_lund.txt \n"; 
#        printf SCRIPT_FILE "OUTPUT_TEMPLATE:  /lustre/expphy/volatile/eic/parkkj/jleic_kinematics/source_codes2016_for_git_hub_tdis_v1/ifarmbatch/lund_out/$outlunds\n";                           
        close(SCRIPT_FILE);
        system("jsub $S_script_name");
        print "Job jsc$rnum is launched \n";


#
################################################
sub print_usage{
#
        print <<ALL;
exec_sim: Creates a script to run JLEIC Spectator Tagging 
                  MC simulation on the batch farm and
                  copy results to the desired locations.
                  Only required argument is a run number.
                  Rest of arguments have their defaults.
ALL
                return;
#
}
