*CMZ :  2.08/00 06/06/99  15.38.27  by  Hannes Jung
*CMZ :  2.07/03 15/05/99  14.25.17  by  Hannes Jung
*-- Author :    Hannes Jung   03/04/94
      FUNCTION ALPHAS(RQ)
      IMPLICIT NONE
      Integer NF
      REAL ALAM
      COMMON/ALPHA/NF,ALAM
*KEEP,RGPARA.
      INTEGER IWEI
      DOUBLE PRECISION ALPHS,PI,ALPH
      COMMON /PARAM/ ALPHS,PI,ALPH,IWEI
      DOUBLE PRECISION SIN2W,XMW2
      COMMON/ELWEAK/SIN2W,XMW2
      DOUBLE PRECISION PT2CUT,THEMA,THEMI,Q2START,W_Q2,OMEG2
      INTEGER IRUNA,IQ2,IRUNAEM
      INTEGER IPRO
      COMMON/RAPA /IPRO,IRUNA,IQ2,IRUNAEM,Q2START,W_Q2,OMEG2
      DOUBLE PRECISION SCALFA
      COMMON/SCALF/ SCALFA
      COMMON/PTCUT/ PT2CUT(100)
      COMMON/ELECT/ THEMA,THEMI
      REAL ULALPS,ULALEM
      EXTERNAL ULALPS,ULALEM
C     SAVE


*KEEP,RGPYPARS.
      INTEGER IPYPAR
      PARAMETER (IPYPAR=200)
      REAL PARP
      INTEGER MSTP
      COMMON/PYPARS/MSTP(IPYPAR),PARP(IPYPAR)
C      SAVE

*KEEP,RGDISDIF.
      INTEGER IDIR,IDISDIF
      COMMON/DISDIF/ IDIR,IDISDIF
*KEEP,RGLUDAT1.
      REAL PARU,PARJ
      INTEGER MSTU,MSTJ
      COMMON/LUDAT1/MSTU(200),PARU(200),MSTJ(200),PARJ(200)
C      SAVE

*KEEP,RGDIFFR.
      INTEGER NG,NPOM
      DOUBLE PRECISION T2MAX,XF,ALPHP,RN2,EPSP,QMI,YMI,QMA,YMA
      COMMON/DIFFR/T2MAX,XF,ALPHP,RN2,EPSP,QMI,YMI,QMA,YMA,NG,NPOM
      INTEGER IREM
      COMMON/PREMNANT/IREM
*KEND.
      REAL SNGL
	Double Precision ALPHAS,RQ,RQ1
C PDFLIB COMMON
      Double Precision QCDL4,QCDL5
      COMMON/W50512/ QCDL4,QCDL5
C
      REAL SCALE
      RQ1 = RQ
      IF(IRUNA.EQ.0) THEN
         ALPHAS=ALPHS
      ELSE

         SCALE = SNGL(RQ1*RQ1)
         ALPHAS =DBLE(ULALPS(SCALE))
      ENDIF
c      write(6,*) alphas,nf
      RETURN
      END
