*CMZ :  2.07/03 15/05/99  14.38.44  by  Hannes Jung
*-- Author :    Hannes Jung   03/04/94
      SUBROUTINE DIFFR1(X,WDIF)
      IMPLICIT NONE
*KEEP,RGPARAS.
      DOUBLE PRECISION PT2CUT,THEMA,THEMI,Q2START,W_Q2,OMEG2
      INTEGER IRUNA,IQ2,IRUNAEM
      INTEGER IPRO
      COMMON/RAPA /IPRO,IRUNA,IQ2,IRUNAEM,Q2START,W_Q2,OMEG2
      DOUBLE PRECISION SCALFA
      COMMON/SCALF/ SCALFA
      COMMON/PTCUT/ PT2CUT(100)
      COMMON/ELECT/ THEMA,THEMI
      REAL ULALPS,ULALEM
      EXTERNAL ULALPS,ULALEM
C     SAVE

*KEEP,RGHS45.
      INTEGER IHERAC,KPAHS
      DOUBLE PRECISION YHS,XHS,Q2HS
      COMMON /HS45/ IHERAC,KPAHS,YHS,XHS,Q2HS
*KEND.
      Double Precision GEV2NB,WPART,WDIF,WT1
	Double Precision X(20)
      DATA GEV2NB/.3893857D+6/
      WPART=0.D0
      WDIF=0.D0
      WT1=0.D0
      IF(IHERAC.EQ.0) THEN
         CALL PARTDF(X,WPART)
      ELSE
         CALL PARTDFHS(X,WPART)
      ENDIF

      IF(WPART.GT.0.) THEN
         IF(IPRO.EQ.10) CALL ELEQQL(WT1)
         IF(IPRO.EQ.13) CALL ELEQQF(WT1)
         IF(IPRO.EQ.15) CALL ELEQCDC(WT1)
         WDIF=WPART*WT1*GEV2NB
      ENDIF
c      if(wt1.eq.0.d0.and.wpart.ne.0.d0) then
c      write(6,*) 'diffr1 wpart,wt1',wpart,wt1
c      endif
      RETURN
      END
