*CMZ :  2.07/03 15/05/99  14.59.27  by  Hannes Jung
*-- Author :    Hannes Jung   03/04/94
      SUBROUTINE DUSHOW(I1,I2,QMAX)
	IMPLICIT NONE
      INTEGER N,K
      REAL P,V,QMAX
      DOUBLE PRECISION DP
*KEEP,RGLUPARM.
      INTEGER LUPAN
      PARAMETER (LUPAN=4000)


*KEND.
      COMMON/LUJETS/N,K(LUPAN,5),P(LUPAN,5),V(LUPAN,5)
      COMMON/DUJETS/DP(LUPAN,5)
	INTEGER I1,I2,I,J
	
      DO 10 I=1,N
         DO 10 J=1,5
   10 P(I,J)= SNGL(DP(I,J))
      CALL LUSHOW(I1,I2,QMAX)
      DO 20 I=1,N
         DO 20 J=1,5
   20 DP(I,J)= DBLE(P(I,J))
      RETURN
      END
