*CMZ :  2.08/00 14/06/99  19.13.55  by  Hannes Jung
*CMZ :  2.07/03 15/05/99  18.29.44  by  Hannes Jung
*-- Author :    Hannes Jung   03/04/94
      SUBROUTINE ELEQQB(WT1)
      IMPLICIT NONE
C
C    PHOTON GLUON ----> Q Q_BAR
C
C         P1(G)-----//////--------Q1(C)
C                  ////////
C         P2(PH)-----//////--------Q2(CBAR)
C
C
C  ( EICHLER KUNSZT ETH-PT/88-1 SOME PROBLEMS WITH AVERAGED SPIN
C  ( AND COLOUR
C  ( USE ELLIS KUNSZT CALCULATION IN NUCL PHYS. B303 (1988) 653
C  (
C

*KEEP,RGLUJETS.
      INTEGER N,K
      REAL SP,V
      DOUBLE PRECISION P
      INTEGER LUPAN
      PARAMETER (LUPAN=4000)


      COMMON/LUJETS/N,K(LUPAN,5),SP(LUPAN,5),V(LUPAN,5)
      COMMON/DUJETS/P(LUPAN,5)
      REAL ULMASS
      DOUBLE PRECISION DOT1,DPLU,DLANGL
      EXTERNAL DLANGL,ULMASS,DPLU,LUCHGE,DOT1
C      SAVE

*KEEP,RGPARA1.
      DOUBLE PRECISION SHAT,YMAX,YMIN,Q2,Q2MAX,Q2MIN
      DOUBLE PRECISION XMAX,XMIN,Q2Q,AM,PCM
      COMMON /PARAT/AM(18),SHAT,YMAX,YMIN,Q2MAX,Q2MIN,XMAX,XMIN
      COMMON /PARAE/Q2,Q2Q,PCM(4,18)
C      SAVE
*KEEP,RGPARA.
      INTEGER IWEI
      DOUBLE PRECISION ALPHS,PI,ALPH
      COMMON /PARAM/ ALPHS,PI,ALPH,IWEI
      DOUBLE PRECISION SIN2W,XMW2
      COMMON/ELWEAK/SIN2W,XMW2
      DOUBLE PRECISION PT2CUT,THEMA,THEMI,Q2START,W_Q2,OMEG2
      INTEGER IRUNA,IQ2,IRUNAEM
      INTEGER IPRO
      COMMON/RAPA /IPRO,IRUNA,IQ2,IRUNAEM,Q2START,W_Q2,OMEG2
      DOUBLE PRECISION SCALFA
      COMMON/SCALF/ SCALFA
      COMMON/PTCUT/ PT2CUT(100)
      COMMON/ELECT/ THEMA,THEMI
      REAL ULALPS,ULALEM
      EXTERNAL ULALPS,ULALEM
C     SAVE


*KEEP,RGLUCO.
      REAL PLEPIN,PPIN
      INTEGER KE,KP,KEB,KPH,KGL,KPA,NFRAG,ILEPTO,IFPS,IHF,IALMKT
      INTEGER INTER,ISEMIH
      INTEGER NIA1,NIR1,NIA2,NIR2,NF1,NF2,NFT,NFLAV,NFLQCDC
      COMMON/LUCO  /KE,KP,KEB,KPH,KGL,KPA,NFLAV,NFLQCDC
      COMMON/INPU  /PLEPIN,PPIN,NFRAG,ILEPTO,IFPS,IHF,IALMKT,INTER,
     +              ISEMIH
      COMMON/HARD/ NIA1,NIR1,NIA2,NIR2,NF1,NF2,NFT
      INTEGER IHFLA
      COMMON/HFLAV/ IHFLA
C      SAVE

*KEEP,RGPART.
      DOUBLE PRECISION SSS,CM,DBCMS
      DOUBLE PRECISION PBEAM
      INTEGER KBEAM,KINT
      COMMON /PARTON/ SSS,CM(4),DBCMS(4)
      COMMON /BEAM/PBEAM(2,5),KBEAM(2,5),KINT(2,5)
C      SAVE


*KEEP,RGRAPGKI.
      REAL YY,XEL,XPR,PT2H,SHH,T2GKI,XFGKI
      COMMON/RAPGKI/ YY,XEL,XPR,PT2H,SHH,T2GKI,XFGKI
      REAL ZQGKI,XPGKI,PHITGKI
      COMMON/MEINFO/ZQGKI,XPGKI,PHITGKI
C     SAVE

*KEND.
      Double Precision ALPHAS,ALPHA_S,QF,SH,TH,UH,V1,V2,SUM2
      Double Precision ALPH_EM,WT1
      INTEGER LUCHGE
      IF(INTER.EQ.2) THEN
         write(6,*) ' INTER = 2 not implemented for eleqqb'
         STOP
      ENDIF
      QF=DFLOAT(LUCHGE(KPA))/3.D0
      ALPHA_S=ALPHAS(DSQRT(Q2Q))
      SH = 2.D0 * AM(1)**2 + 2.D0 * DOT1(NF1,NF2)
      TH = AM(1)**2 - 2.D0 * DOT1(NIA1,NF1) - P(NIA1,5)**2
      UH = AM(2)**2 - 2.D0 * DOT1(NIA1,NF2) - P(NIA1,5)**2
c      write(6,*) ' ELEQQB ',QG2
C.....MARTIX ELEMENT
      V1 = AM(1)**2 - TH
      V2 = AM(1)**2 - UH
      SUM2 = V1/V2 + V2/V1 + 4.D0*AM(1)**2 *SH/V1/V2 -4.D0*AM(1)**4
     +*SH*SH/V1/V1/V2/V2
c      write(6,*) ' old sum2 : ',sum2
c      write(6,*) ' sss ',sss
cccccccccccccc         SUM2 = SUM2/QG2**2

      ALPH_EM = ALPH
      IF(IRUNAEM.EQ.1) ALPH_EM = DBLE(ULALEM(SNGL(Q2)))

      SUM2 = SUM2*16.D0*PI*PI*ALPHA_S*ALPH_EM*QF*QF
      WT1=SUM2
      RETURN
      END
