*CMZ :  2.08/00 14/06/99  19.13.55  by  Hannes Jung
*CMZ :  2.07/03 15/05/99  20.34.44  by  Hannes Jung
*-- Author :    Hannes Jung   03/04/94
      FUNCTION FXN1(X,WEIGHT)
      IMPLICIT NONE
      Double Precision X,WEIGHT,WEIG,FXN1
      DIMENSION X(20)
      Integer Ncall,I,J
*KEEP,RGLUJETS.
      INTEGER N,K
      REAL SP,V
      DOUBLE PRECISION P
      INTEGER LUPAN
      PARAMETER (LUPAN=4000)


      COMMON/LUJETS/N,K(LUPAN,5),SP(LUPAN,5),V(LUPAN,5)
      COMMON/DUJETS/P(LUPAN,5)
      REAL ULMASS
      DOUBLE PRECISION DOT1,DPLU,DLANGL
      EXTERNAL DLANGL,ULMASS,DPLU,LUCHGE,DOT1
C      SAVE

*KEEP,RGPARAS.
      DOUBLE PRECISION PT2CUT,THEMA,THEMI,Q2START,W_Q2,OMEG2
      INTEGER IRUNA,IQ2,IRUNAEM
      INTEGER IPRO
      COMMON/RAPA /IPRO,IRUNA,IQ2,IRUNAEM,Q2START,W_Q2,OMEG2
      DOUBLE PRECISION SCALFA
      COMMON/SCALF/ SCALFA
      COMMON/PTCUT/ PT2CUT(100)
      COMMON/ELECT/ THEMA,THEMI
      REAL ULALPS,ULALEM
      EXTERNAL ULALPS,ULALEM
C     SAVE

*KEEP,RGPART.
      DOUBLE PRECISION SSS,CM,DBCMS
      DOUBLE PRECISION PBEAM
      INTEGER KBEAM,KINT
      COMMON /PARTON/ SSS,CM(4),DBCMS(4)
      COMMON /BEAM/PBEAM(2,5),KBEAM(2,5),KINT(2,5)
C      SAVE


*KEEP,RGDISDIF.
      INTEGER IDIR,IDISDIF
      COMMON/DISDIF/ IDIR,IDISDIF
*KEND.
      DATA NCALL/0/
      DO 10  I=1,20
         DO 10 J=1,5
            K(I,J) = 0
   10 P(I,J) = 0.0D0
      N=0
      WEIG=0.D0
      FXN1=0.D0
      IF(IDIR.EQ.0) THEN
         IF(IPRO.EQ.10.OR.IPRO.EQ.13.OR.IPRO.EQ.15) THEN
            CALL DIFFR1(X,WEIG)
         ELSEIF(IPRO.EQ.11.OR.IPRO.EQ.14) THEN
            CALL DIFFR2(X,WEIG)
         ELSEIF(IPRO.EQ.12) THEN
            CALL DIFFR3(X,WEIG)
         ELSEIF(IPRO.EQ.18) THEN
            CALL DIFFR7(X,WEIG)
         ELSEIF(IPRO.EQ.20) THEN
            CALL DIFFR5(X,WEIG)
         ELSEIF(IPRO.EQ.21) THEN
            CALL DIFFR6(X,WEIG)
         ELSEIF(IPRO.EQ.30) THEN
            CALL DIFFR30(X,WEIG)
         ELSEIF(IPRO.EQ.100) THEN
            CALL DIFFR4(X,WEIG)
         ELSE
            WRITE(6,*) ' FXN1: wrong subprocess selected; IPRO = ',
     +      IPRO
            WRITE(6,*) ' FXN1: PROGRM STOPPED '
            STOP
         ENDIF
      ELSEIF(IDIR.EQ.1) THEN
         IF(IPRO.EQ.10.OR.IPRO.EQ.13.OR.IPRO.EQ.15) THEN
            CALL DIR1(X,WEIG)
         ELSEIF(IPRO.EQ.11.OR.IPRO.EQ.14) THEN
            CALL DIR2(X,WEIG)
         ELSEIF(IPRO.EQ.12) THEN
            CALL DIR3(X,WEIG)
         ELSEIF(IPRO.EQ.18) THEN
            CALL DIR4(X,WEIG)
         ELSEIF(IPRO.EQ.99) THEN
            CALL DIR99(X,WEIG)
         ELSE
            WRITE(6,*) ' FXN1: wrong subprocess selected; IPRO = ',
     +      IPRO
            WRITE(6,*) ' FXN1: PROGRM STOPPED '
            STOP
         ENDIF
      ENDIF
C BOOST BACK TO OVERALL CMS
c      write(6,*) '  FXN1 ',weig,X
      IF(WEIG.EQ.0.0) RETURN
      IF(IPRO.EQ.20.OR.IPRO.EQ.21.OR.IPRO.EQ.30) THEN
      ELSE
         IF(IPRO.NE.12.OR.IPRO.EQ.100) CALL DUDBRB(0,N,0.D0,0.D0,
     +   DBCMS(1)/DBCMS(4),DBCMS(2)/DBCMS(4), DBCMS(3)/DBCMS(4))
      ENDIF
      ncall = ncall + 1
c      call dulist(1)
      FXN1=WEIG
      WEIGHT = WEIG
      RETURN
      END
