*CMZ :  2.08/00 14/06/99  19.13.55  by  Hannes Jung
*CMZ :  2.07/03 15/05/99  21.55.59  by  Hannes Jung
*-- Author :    Hannes Jung   03/04/94
      SUBROUTINE LSCALE(INFIN,QMAX)
      IMPLICIT NONE
      REAL QMAX
*KEEP,RGFULL.
      INTEGER IFULL,IQCDGRID
      COMMON /OALPINI/ IFULL,IQCDGRID
*KEEP,RGPARA1.
      DOUBLE PRECISION SHAT,YMAX,YMIN,Q2,Q2MAX,Q2MIN
      DOUBLE PRECISION XMAX,XMIN,Q2Q,AM,PCM
      COMMON /PARAT/AM(18),SHAT,YMAX,YMIN,Q2MAX,Q2MIN,XMAX,XMIN
      COMMON /PARAE/Q2,Q2Q,PCM(4,18)
C      SAVE
*KEEP,RGPARAS.
      DOUBLE PRECISION PT2CUT,THEMA,THEMI,Q2START,W_Q2,OMEG2
      INTEGER IRUNA,IQ2,IRUNAEM
      INTEGER IPRO
      COMMON/RAPA /IPRO,IRUNA,IQ2,IRUNAEM,Q2START,W_Q2,OMEG2
      DOUBLE PRECISION SCALFA
      COMMON/SCALF/ SCALFA
      COMMON/PTCUT/ PT2CUT(100)
      COMMON/ELECT/ THEMA,THEMI
      REAL ULALPS,ULALEM
      EXTERNAL ULALPS,ULALEM
C     SAVE

*KEEP,RGLUJETS.
      INTEGER N,K
      REAL SP,V
      DOUBLE PRECISION P
      INTEGER LUPAN
      PARAMETER (LUPAN=4000)


      COMMON/LUJETS/N,K(LUPAN,5),SP(LUPAN,5),V(LUPAN,5)
      COMMON/DUJETS/P(LUPAN,5)
      REAL ULMASS
      DOUBLE PRECISION DOT1,DPLU,DLANGL
      EXTERNAL DLANGL,ULMASS,DPLU,LUCHGE,DOT1
C      SAVE

*KEEP,RGDISDIF.
      INTEGER IDIR,IDISDIF
      COMMON/DISDIF/ IDIR,IDISDIF
*KEND.
      INTEGER INFIN
      IF(IFULL.EQ.0) THEN
         IF(IPRO.EQ.12) THEN
            QMAX = SNGL(Q2)
         ELSE
            QMAX = SNGL(P(27,5))**2
            IF(INFIN.LT.0) THEN
               IF(IPRO.EQ.18) THEN
                  QMAX = SNGL(Q2Q)
               ELSE
                  QMAX=SNGL(MAX(ABS(-Q2-2.D0*DOT1(25,21)), ABS(-Q2-
     +            2.D0* DOT1(26,21))))
               ENDIF
            ENDIF
         ENDIF
      ELSE
         IF(IPRO.EQ.12) THEN
            QMAX = 4.*SNGL(PT2CUT(13))
         ELSE
            QMAX = SNGL(P(27,5))**2
            IF(IPRO.EQ.99) QMAX = SNGL(P(28,5))**2
            IF(INFIN.LT.0) QMAX=SNGL(MAX(ABS(-Q2-2.D0*DOT1(25,21)),
     +      ABS(-Q2-2.D0*DOT1(26,21))))
            IF(IPRO.EQ.99.and.INFIN.LT.0) THEN
               QMAX=SNGL(MAX(ABS(-Q2-2.D0*DOT1(25,21)), ABS(-Q2-2.D0*
     +         DOT1(27,21))))
            ENDIF
         ENDIF
      ENDIF
      QMAX=SQRT(QMAX)
      RETURN
      END
