*CMZ :  2.07/03 16/05/99  09.41.48  by  Hannes Jung
*-- Author :    Hannes Jung   15/03/95
      SUBROUTINE PARTHS(X,WPART)
      IMPLICIT NONE
*KEEP,RGDISDIF.
      INTEGER IDIR,IDISDIF
      COMMON/DISDIF/ IDIR,IDISDIF
*KEEP,RGLUJETS.
      INTEGER N,K
      REAL SP,V
      DOUBLE PRECISION P
      INTEGER LUPAN
      PARAMETER (LUPAN=4000)


      COMMON/LUJETS/N,K(LUPAN,5),SP(LUPAN,5),V(LUPAN,5)
      COMMON/DUJETS/P(LUPAN,5)
      REAL ULMASS
      DOUBLE PRECISION DOT1,DPLU,DLANGL
      EXTERNAL DLANGL,ULMASS,DPLU,LUCHGE,DOT1
C      SAVE

*KEND.
	Double PRecision X,WPART
      DIMENSION X(20)
      IF(IDIR.EQ.0) THEN
         CALL PARTDFHS(X,WPART)
      ELSE
         CALL PARTDIHS(X,WPART)
      ENDIF
      RETURN
      END
