      FUNCTION XGLU(XX,QQ2)
	Implicit none
      DOUBLE PRECISION XX,XGX,QQ2,XGLU
      DOUBLE PRECISION XXX,QQ,UPV,DNV,USEA,DSEA,STR,CHM,BOT,TOP,GLU,
     +VAL(20)
      LOGICAL PDFFIRST
      COMMON /W50516/PDFFIRST
      CHARACTER*20 PARM(20)
*KEEP,RGPYPARS.
      INTEGER IPYPAR
      PARAMETER (IPYPAR=200)
      REAL PARP
      INTEGER MSTP
      COMMON/PYPARS/MSTP(IPYPAR),PARP(IPYPAR)
C      SAVE

*KEND.
      Integer MST51,NPDF
      DATA NPDF/0/,UPV,DNV,USEA,DSEA,STR,CHM,BOT,TOP,GLU/9*0.D0/
      QQ=SQRT(MAX(0.D0,QQ2))
      XXX = XX
      PARM(1) = 'NPTYPE'
      MST51 = MSTP(51)
      VAL(1) = INT(MST51/1000000)

      PARM(2) = 'NGROUP'
      VAL(2) = DBLE(MOD(MST51,1000000)/1000)
      PARM(3) = 'NSET'
      VAL(3) = DBLE(MOD(MOD(MST51,1000000),1000))
CNEW
      NPDF=NPDF+1
      PDFFIRST=.FALSE.
      IF(NPDF.LE.1) PDFFIRST=.TRUE.
c call PDFSET each time, because when DIF with pi structure function is
c also selected one would get in confusion....
      CALL PDFSET(PARM,VAL)
      CALL STRUCTM(XXX,QQ,UPV,DNV,USEA,DSEA,STR,CHM,BOT,TOP,GLU)
      XGLU = GLU
      RETURN
      END
