

      FUNCTION XGX(QQ2)
	Implicit none
      DOUBLE PRECISION X,XGX,QQ2
      COMMON/gluon/X
      DOUBLE PRECISION XXX,Q2,GLU,XGLU
	EXTERNAL XGLU
      Q2=QQ2
      XXX = X
      XGX = XGLU(XXX,QQ2)
      RETURN
      END
